language: node_js
node_js:
  - "12.13"
cache:
  yarn: true  

install:
  - yarn
script:
  - if [ -n "$TRAVIS_TAG" ]; then yarn workspace @offcourse/public-badges-backend deploy:pilot; fi
  - yarn workspace @offcourse/public-badges-drawer build
  - if [ -n "$TRAVIS_TAG" ]; then node node_modules/.bin/workspace-publish; fi
