service: public-badges
plugins:
  - serverless-domain-manager
custom:
  customDomain:
    domainName: api.publicbadges.com
    stage: ${opt:stage}
    basePath: ${opt:stage}
    createRoute53Record: true
  registry_bucket: public-badges-registry-${opt:stage}
  registry_lookup_table: registry-lookup-${opt:stage}
  api: public-badges.api-${opt:stage}
  save_organization: public-badges.save-organization-${opt:stage}
  save_badge: public-badges.save-badge-${opt:stage}
  approve_organization: public-badges.approve-organization-${opt:stage}
  prepare_open_badge_artifact: public-badges.prepare-open-badge-artifact-${opt:stage}
  update_registry_lookup: public-badges.update-registry-lookup-${opt:stage}
  run_value_case_scenarios: public-badges.run-value-case-scenarios-${opt:stage}
  sign_open_badge_artifact: public-badges.sign-open-badge-artifact-${opt:stage}
  echo: public-badges.echo-${opt:stage}
  organization-status-index: organization-status-${opt:stage}
provider:
  name: aws
  runtime: nodejs10.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
        - s3:PutObject
        - s3:PutObjectAcl
      Resource:
        - arn:aws:s3:::${self:custom.registry_bucket}
        - arn:aws:s3:::${self:custom.registry_bucket}/*
    - Effect: Allow
      Action:
        - events:PutEvents
      Resource: "*"
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:${opt:region,
          self:provider.region}:*:table/${self:custom.registry_lookup_table}
        - arn:aws:dynamodb:${opt:region,
          self:provider.region}:*:table/${self:custom.registry_lookup_table}/index/*
package:
  exclude:
    - dist/assets
    - node_modules
  include:
    - node_modules/voca/**/*
    - node_modules/uuid/**/*
    - node_modules/ramda/**/*
    - node_modules/module-alias/**/*
    - node_modules/jws/**/*
functions:
  graphql:
    handler: dist/index.graphql
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
      - http:
          path: playground
          method: any
          cors: true
    environment:
      HANDLER_NAME: ${self:custom.api}
      REGISTRY_BUCKET: ${self:custom.registry_bucket}
      REGISTRY_LOOKUP_TABLE: ${self:custom.registry_lookup_table}
      ORGANIZATION_STATUS_INDEX: ${self:custom.organization_status_index}
    package:
      individually: true
      exclude:
        - node_modules
        - dist/assets
      include:
        - node_modules/apollo-server-lambda/**/*
        - node_modules/graphql/**/*
        - node_modules/graphql-import-node/**/*
        - node_modules/graphql-playground-middleware-lambda/**/*
        - node_modules/graphql-scalars/**/*
        - node_modules/graphql-tools/**/*
        - node_modules/uuid/**/*
        - node_modules/voca/**/*
        - node_modules/ramda/**/*
  saveOrganization:
    handler: dist/index.saveOrganization
    events:
      - eventBridge:
          pattern:
            detail-type:
              - ORGANIZATION_REGISTRATION_REQUESTED
              - ORGANIZATION_APPROVAL_ACCEPTED
            source:
              - ${self:custom.api}
              - ${self:custom.approve_organization}
    environment:
      HANDLER_NAME: ${self:custom.save_organization}
      REGISTRY_BUCKET: ${self:custom.registry_bucket}
  saveBadge:
    handler: dist/index.saveBadge
    events:
      - eventBridge:
          pattern:
            detail-type:
              - BADGE_ISSUANCE_REQUESTED
              - BADGE_ISSUANCE_APPROVED
              - BADGE_ISSUANCE_REJECTED
              - OPEN_BADGES_ARTIFACT_SIGNED
            source:
              - ${self:custom.api}
              - ${self:custom.run_value_case_scenarios}
              - ${self:custom.sign_open_badge_artifact}
    environment:
      HANDLER_NAME: ${self:custom.save_badge}
      REGISTRY_BUCKET: ${self:custom.registry_bucket}
  approveOrganization:
    handler: dist/index.approveOrganization
    events:
      - eventBridge:
          pattern:
            detail-type:
              - ORGANIZATION_APPROVAL_REQUESTED
            source:
              - ${self:custom.save_organization}
    environment:
      HANDLER_NAME: ${self:custom.approve_organization}
  prepareOpenBadgeArtifact:
    handler: dist/index.prepareOpenBadgeArtifact
    events:
      - eventBridge:
          pattern:
            detail-type:
              - BADGE_ISSUANCE_APPROVED
            source:
              - ${self:custom.run_value_case_scenarios}
    environment:
      HANDLER_NAME: ${self:custom.prepare_open_badge_artifact}
      REGISTRY_BUCKET: ${self:custom.registry_bucket}
  updateRegistry:
    handler: dist/index.updateRegistry
    events:
      - eventBridge:
          pattern:
            detail-type:
              - ORGANIZATION_REGISTRATION_REQUESTED
              - ORGANIZATION_APPROVAL_ACCEPTED
            source:
              - ${self:custom.api}
              - ${self:custom.approve_organization}
    environment:
      HANDLER_NAME: ${self:custom.update_registry_lookup}
      REGISTRY_LOOKUP_TABLE: ${self:custom.registry_lookup_table}
  runValueCaseScenarios:
    handler: dist/index.runValueCaseScenarios
    events:
      - eventBridge:
          pattern:
            detail-type:
              - BADGE_ISSUANCE_REQUESTED
            source:
              - ${self:custom.api}
    environment:
      HANDLER_NAME: ${self:custom.run_value_case_scenarios}
      REGISTRY_BUCKET: ${self:custom.registry_bucket}
  signOpenBadgeArtifact:
    handler: dist/index.signOpenBadgeArtifact
    events:
      - eventBridge:
          pattern:
            detail-type:
              - OPEN_BADGES_ARTIFACT_CREATED
            source:
              - ${self:custom.prepare_open_badge_artifact}
    environment:
      HANDLER_NAME: ${self:custom.sign_open_badge_artifact}
  echo:
    handler: dist/index.echo
    events:
      - s3: ${self:custom.registry_bucket}
      - eventBridge:
          pattern:
            detail-type:
              - BADGE_ISSUANCE_REJECTED
            source:
              - ${self:custom.run_value_case_scenarios}
    environment:
      HANDLER_NAME: ${self:custom.echo}
resources:
  Resources:
    registryLookupTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.registry_lookup_table}
        GlobalSecondaryIndexes:
          - IndexName: organization-status-${opt:stage}
            KeySchema:
              - AttributeName: approvalStatus
                KeyType: HASH
              - AttributeName: organizationId
                KeyType: RANGE
            Projection:
              NonKeyAttributes: []
              ProjectionType: KEYS_ONLY
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: organizationId
            AttributeType: S
          - AttributeName: identityType
            AttributeType: S
          - AttributeName: identityKey
            AttributeType: S
          - AttributeName: approvalStatus
            AttributeType: S
        KeySchema:
          - AttributeName: identityKey
            KeyType: HASH
          - AttributeName: identityType
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
