/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  PublicBadge,
} from './types';

export namespace Components {
  interface MyComponent {}
  interface PublicbadgesCircle {
    'badgesCount': number;
    'colorMode': string;
    'interactive': boolean;
  }
  interface PublicbadgesDrawer {
    'badgeColorMode': string;
    'modalColorMode': string;
    'modalZIndex': string;
  }
  interface PublicbadgesModal {
    'badges': Array<PublicBadge>;
    'modalColorMode': string;
    'modalZIndex': string;
    'top': string;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLPublicbadgesCircleElement extends Components.PublicbadgesCircle, HTMLStencilElement {}
  var HTMLPublicbadgesCircleElement: {
    prototype: HTMLPublicbadgesCircleElement;
    new (): HTMLPublicbadgesCircleElement;
  };

  interface HTMLPublicbadgesDrawerElement extends Components.PublicbadgesDrawer, HTMLStencilElement {}
  var HTMLPublicbadgesDrawerElement: {
    prototype: HTMLPublicbadgesDrawerElement;
    new (): HTMLPublicbadgesDrawerElement;
  };

  interface HTMLPublicbadgesModalElement extends Components.PublicbadgesModal, HTMLStencilElement {}
  var HTMLPublicbadgesModalElement: {
    prototype: HTMLPublicbadgesModalElement;
    new (): HTMLPublicbadgesModalElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'publicbadges-circle': HTMLPublicbadgesCircleElement;
    'publicbadges-drawer': HTMLPublicbadgesDrawerElement;
    'publicbadges-modal': HTMLPublicbadgesModalElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {}
  interface PublicbadgesCircle {
    'badgesCount'?: number;
    'colorMode'?: string;
    'interactive'?: boolean;
  }
  interface PublicbadgesDrawer {
    'badgeColorMode'?: string;
    'modalColorMode'?: string;
    'modalZIndex'?: string;
  }
  interface PublicbadgesModal {
    'badges'?: Array<PublicBadge>;
    'modalColorMode'?: string;
    'modalZIndex'?: string;
    'onCloseDrawer'?: (event: CustomEvent<any>) => void;
    'top'?: string;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'publicbadges-circle': PublicbadgesCircle;
    'publicbadges-drawer': PublicbadgesDrawer;
    'publicbadges-modal': PublicbadgesModal;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'publicbadges-circle': LocalJSX.PublicbadgesCircle & JSXBase.HTMLAttributes<HTMLPublicbadgesCircleElement>;
      'publicbadges-drawer': LocalJSX.PublicbadgesDrawer & JSXBase.HTMLAttributes<HTMLPublicbadgesDrawerElement>;
      'publicbadges-modal': LocalJSX.PublicbadgesModal & JSXBase.HTMLAttributes<HTMLPublicbadgesModalElement>;
    }
  }
}


